import 'package:dots_design_system/core/constants.dart';
import 'package:dots_design_system/theme/typography/dots_typo_models.dart';
import 'package:flutter/widgets.dart';

class DotsTypo {
  static DotsTypoModel all(Color color) {
    return DotsTypoModel(
      main: main(color),
      number: number(color),
      secondary: secondary(color),
    );
  }

  static DotsTypoMainModel main(Color color) {
    return DotsTypoMainModel(
      titleH1: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.25,
        letterSpacing: 0.13,
      ),
      titleH2: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 29,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.24,
      ),
      titleH3: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 26,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.23,
      ),
      titleH4: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 23,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.26,
        letterSpacing: -0.02,
      ),
      titleH5: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.25,
        letterSpacing: -0.09,
      ),
      titleH6: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w600,
        height: 1.28,
        letterSpacing: -0.08,
      ),
      bodyLargeRegular: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        height: 1.31,
        letterSpacing: -0.05,
      ),
      bodyLargeMedium: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w500,
        height: 1.31,
        letterSpacing: -0.05,
      ),
      bodyLargeBold: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.31,
        letterSpacing: -0.05,
      ),
      bodyDefaultRegular: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        height: 1.29,
        letterSpacing: -0.02,
      ),
      bodyDefaultMedium: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w500,
        height: 1.29,
        letterSpacing: -0.02,
      ),
      bodyDefaultBold: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        height: 1.29,
        letterSpacing: -0.02,
      ),
      labelDefaultRegular: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        height: 1.31,
        letterSpacing: -0.01,
      ),
      labelDefaultBold: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w600,
        height: 1.31,
        letterSpacing: -0.01,
      ),
      labelSmallRegular: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        height: 1.27,
        letterSpacing: 0.01,
      ),
      labelSmallMedium: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w600,
        height: 1.27,
        letterSpacing: 0.01,
      ),
    );
  }

  static DotsTypoNumberModel number(Color color) {
    return DotsTypoNumberModel(
      numTitleH1: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 32,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.25,
      ),
      numTitleH2: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 29,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.24,
      ),
      numTitleH3: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 26,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.23,
      ),
      numTitleH4: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 23,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.26,
      ),
      numTitleH5: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 20,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.25,
      ),
      numTitleH6: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 18,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.28,
      ),
      numBodyLarge: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 16,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.31,
      ),
      numBodyDefault: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 14,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.29,
      ),
      numLabelDefault: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 13,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.31,
      ),
      numLabelSmall: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 11,
        fontFamily: 'Proxima Soft',
        fontWeight: FontWeight.w700,
        height: 1.27,
      ),
    );
  }

  static DotsTypoSecondaryModel secondary(Color color) {
    return DotsTypoSecondaryModel(
      title02H1: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 32,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.25,
        letterSpacing: 0.13,
      ),
      title02H2: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 29,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.24,
      ),
      title02H3: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 26,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.23,
      ),
      title02H4: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 23,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.26,
        letterSpacing: -0.02,
      ),
      title02H5: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 20,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.25,
        letterSpacing: -0.09,
      ),
      title02H6: TextStyle(
        color: color,
        package: dotsDesignSystemPackage,
        fontSize: 18,
        fontFamily: 'P22 Mackinac',
        fontWeight: FontWeight.w500,
        height: 1.28,
        letterSpacing: -0.08,
      ),
    );
  }
}
